name: feature_orders
description: Orders feature package for the Ashachar Marketplace.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
